### ISSUE TITLE
pkgdown web site not building

### ISSUE THREAD

**Issue by mdozmorov** [Kayla-Morrell/CreateAPackage#2]
The https://kayla-morrell.github.io/CreateAPackage/ page shows 404 Error.

**Comment by lwaldron** [comment]
Perhaps will be fixed in https://github.com/Kayla-Morrell/CreateAPackage/pull/3

**Comment by mdozmorov** [comment]
Still not fixed.

**Comment by Kayla-Morrell** [comment]
I'm not sure what else I can do to fix this. I've coped over files from Sean's workshop repo, I've looked at other workshop repos that have been able to get the pkgdown website to build, all of my files look similar. Is there something I'm missing?

**Comment by mdozmorov** [comment]
I can't find anything wrong either. `pkgdown::build_site()` creates the site locally. @seandavi, can you help?

**Comment by lwaldron** [comment]
Your pkgdown site is correctly built in the gh-pages branch. Have you activated it in your settings? It should look like this:

![image](https://user-images.githubusercontent.com/639942/87717707-20b39400-c7b1-11ea-98b9-2a7022a7cfd7.png)

**Comment by seandavi** [comment]
I think @lwaldron is right on. Your docs are already there, just not being published:

https://github.com/Kayla-Morrell/CreateAPackage/tree/gh-pages

You are just a couple of clicks away!

**Comment by Kayla-Morrell** [comment]
Thanks @lwaldron and @seandavi for the suggestions!

I checked my settings, it seemed to be activated. 

<img width="878" alt="Screen Shot 2020-07-16 at 4 54 03 PM" src="https://user-images.githubusercontent.com/32339524/87721783-ffd54980-c784-11ea-8662-4b577e023694.png">

But then I actually went to the drop down menu and selected `gh-pages branch` and now the message about my site being ready to be published has appeared (with other info about custom domain and enforce HTTPS).

<img width="873" alt="Screen Shot 2020-07-16 at 4 57 34 PM" src="https://user-images.githubusercontent.com/32339524/87722074-7a05ce00-c785-11ea-8953-0edc4b986054.png">

Though now it doesn't say "Your site is published at..." like Levi's does. Should I do a version bump or something to trigger it?

**Comment by seandavi** [comment]
I don't have a good answer for you, @Kayla-Morrell, but this help page suggests trying triggering a push:

https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#troubleshooting-publishing-problems-with-your-github-pages-site

So, yes, you might try a version bump (or really any push to the master branch) which should run the github actions again.

**Comment by Kayla-Morrell** [comment]
Did the version bump and now I see this...

<img width="843" alt="Screen Shot 2020-07-16 at 5 15 57 PM" src="https://user-images.githubusercontent.com/32339524/87723626-0e713000-c788-11ea-9c76-18c23de45abb.png">

but still a 404 error when I follow the link. Hoping it just needs to catch up!

**Comment by seandavi** [comment]
Try a different browser. I think you might be seeing the cache. I see your website now!

![image](https://user-images.githubusercontent.com/92435/87723999-a96a0a00-c788-11ea-91c8-e2c12645d634.png)

**Comment by mdozmorov** [comment]
Everything looks good, thanks, @lwaldron, @seandavi
